version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      # Decode the google-services.json file from the environment variables and save in environment
      - run:
          name: Decode google-services.json from env-vars
          command: echo $ENCODED_GOOGLE_SERVICE_JSON | base64 --decode > app/google-services.json
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlint
      - run:
          name: Run user lint
          command: ./gradlew lintUserDebug
      - run:
          name: Run moderator lint
          command: ./gradlew lintModeratorDebug
      - run:
          name: Run user unit tests
          command: ./gradlew testUserDebugUnitTest
      - run:
          name: Run moderator unit tests
          command: ./gradlew testModeratorDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results